server:
  port: 8080
    
spring:
  application:
    name: cliente-service
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: cliente

client:
  via-cep:
    url: https://viacep.com.br/ws
